(() => {
  'use strict';
  const dishes = [
    {id:'pasta',cat:'hot',price:890,weight:'320 г / g',image:'dish-pasta.png',ru:['Паста Альфредо','Сливочный соус, пармезан и свежие травы.','Тальятелле соединяем с нежным сливочным соусом, выдержанным пармезаном и чёрным перцем. Подаём сразу после приготовления, с ароматной петрушкой.','Паста, сливки, пармезан, сливочное масло, петрушка. Аллергены: пшеница, молоко, яйца.'],en:['Alfredo pasta','Creamy sauce, Parmesan and fresh herbs.','Tagliatelle tossed in a silky cream sauce with aged Parmesan and black pepper. Served freshly made and finished with parsley.','Pasta, cream, Parmesan, butter, parsley. Allergens: wheat, milk, eggs.']},
    {id:'steak',cat:'hot',price:1490,weight:'350 г / g',image:'dish-steak.png',ru:['Стейк с травами','Говядина на гриле с чесночным маслом.','Обжариваем стейк на сильном огне до румяной корочки. Добавляем чесночное масло с розмарином и подаём с овощами гриль. Степень прожарки уточните у официанта.','Говядина, сливочное масло, чеснок, розмарин, сезонные овощи. Аллерген: молоко.'],en:['Herb-grilled steak','Grilled beef with garlic butter.','Seared over high heat for a rich crust, topped with rosemary garlic butter and served with grilled vegetables. Tell your waiter your preferred doneness.','Beef, butter, garlic, rosemary, seasonal vegetables. Allergen: milk.']},
    {id:'bowl',cat:'starters',price:790,weight:'300 г / g',image:'dish-boul.png',ru:['Боул с киноа','Цветные овощи и лёгкая лимонная заправка.','Рассыпчатая киноа, свежие овощи и зелень в одной яркой тарелке. Лимонная заправка подчёркивает вкус ингредиентов, а семечки добавляют приятный хруст.','Киноа, томаты, огурец, листовая зелень, семечки, оливковое масло, лимон.'],en:['Quinoa bowl','Colourful vegetables and a light lemon dressing.','Fluffy quinoa, crisp vegetables and leafy greens in one vibrant bowl. A lemon dressing lifts the flavours while seeds add a satisfying crunch.','Quinoa, tomatoes, cucumber, leafy greens, seeds, olive oil, lemon.']},
    {id:'salad',cat:'starters',price:590,weight:'250 г / g',image:'amber-salad.jpg',ru:['Зелёный сад','Хрустящий салат с сезонными овощами.','Лёгкий свежий салат из листовой зелени, сладких томатов и хрустящих овощей. Заправляем оливковым маслом и лимонным соком перед самой подачей.','Листья салата, томаты, огурец, морковь, оливковое масло, лимон.'],en:['Garden salad','A crisp salad of seasonal vegetables.','Fresh leafy greens, sweet tomatoes and crunchy vegetables. Dressed with olive oil and lemon juice just before serving.','Lettuce, tomatoes, cucumber, carrots, olive oil, lemon.']},
    {id:'soup',cat:'starters',price:490,weight:'300 г / g',image:'amber-soup.jpg',ru:['Тёплый овощной боул','Крупа, стручковая фасоль и свежие овощи.','Сытный боул с рассыпчатой крупой, стручковой фасолью и сезонными овощами. Лёгкая заправка и зелень подчёркивают свежесть ингредиентов.','Киноа, стручковая фасоль, томаты, морковь, зелень, оливковое масло.'],en:['Warm vegetable bowl','Grains, green beans and fresh vegetables.','A nourishing bowl of fluffy grains, green beans and seasonal vegetables. Finished with a light dressing and fresh herbs.','Quinoa, green beans, tomatoes, carrots, herbs, olive oil.']},
    {id:'pizza',cat:'hot',price:850,weight:'400 г / g',image:'amber-pizza.jpg',ru:['Пицца с курицей','Курица, томаты, моцарелла и зелень.','Тонкое тесто с воздушным бортиком, томатным соусом, курицей и тягучей моцареллой. После печи добавляем свежий базилик и несколько капель оливкового масла.','Пшеничное тесто, курица, томаты, моцарелла, базилик, оливковое масло. Аллергены: пшеница, молоко.'],en:['Chicken pizza','Chicken, tomatoes, mozzarella and herbs.','Thin pizza dough with a light crust, chicken, tomato sauce and melting mozzarella. Finished with fresh basil and a drizzle of olive oil.','Wheat dough, chicken, tomatoes, mozzarella, basil, olive oil. Allergens: wheat, milk.']},
    {id:'burger',cat:'hot',price:890,weight:'340 г / g',image:'amber-burger.jpg',ru:['Бургер Bobli','Сочная котлета, чеддер и фирменный соус.','Говяжья котлета на гриле в мягкой поджаренной булочке. Дополняем сыром, салатом, томатами и маринованным огурцом. Фирменный соус связывает все вкусы.','Булочка, говядина, чеддер, томат, салат, огурец, соус. Аллергены: пшеница, молоко, яйца, горчица, кунжут.'],en:['Bobli burger','Juicy beef, Cheddar and our signature sauce.','A grilled beef patty in a soft toasted bun with cheese, lettuce, tomato and pickles. Our signature sauce brings all the flavours together.','Bun, beef, Cheddar, tomato, lettuce, pickles, sauce. Allergens: wheat, milk, eggs, mustard, sesame.']},
    {id:'salmon',cat:'hot',price:1390,weight:'300 г / g',image:'amber-salmon.jpg',ru:['Лосось на гриле','Нежное филе с овощами и лимоном.','Филе лосося готовим до нежной текстуры и подаём с овощным гарниром. Лимон и свежая зелень добавляют лёгкость и подчёркивают вкус рыбы.','Лосось, сезонные овощи, лимон, зелень, оливковое масло. Аллерген: рыба.'],en:['Grilled salmon','Tender fillet with vegetables and lemon.','Salmon fillet grilled until tender and served with seasonal vegetables. Lemon and fresh herbs give the dish a bright finish.','Salmon, seasonal vegetables, lemon, herbs, olive oil. Allergen: fish.']},
    {id:'chocolate',cat:'desserts',price:450,weight:'180 г / g',image:'amber-chocolate.jpg',ru:['Шоколадное фондю','Фрукты и сладости с тёплым шоколадом.','Порция фруктов и нежных сладостей с тёплым шоколадным соусом. Обмакивайте кусочки в шоколад и сочетайте вкусы так, как нравится вам.','Шоколад, сливки, сезонные фрукты, бисквит, маршмеллоу. Аллергены: молоко, яйца, пшеница.'],en:['Chocolate fondue','Fruit and sweets with warm chocolate.','A serving of fruit and delicate sweets with warm chocolate sauce. Dip each piece and discover your favourite combinations.','Chocolate, cream, seasonal fruit, sponge cake, marshmallows. Allergens: milk, eggs, wheat.']},
    {id:'cake',cat:'desserts',price:490,weight:'170 г / g',image:'amber-cake.jpg',ru:['Ягодный чизкейк','Сливочная начинка на хрустящей основе.','Нежный чизкейк на основе из песочного печенья. Ягодный соус добавляет свежую кислинку и уравновешивает сладость сливочного сыра.','Сливочный сыр, сливки, печенье, яйца, сахар, ягоды. Аллергены: молоко, яйца, пшеница.'],en:['Berry cheesecake','Creamy filling on a crisp biscuit base.','Smooth cheesecake on a buttery biscuit base. A berry topping adds freshness and balances the richness of the cream cheese.','Cream cheese, cream, biscuits, eggs, sugar, berries. Allergens: milk, eggs, wheat.']},
    {id:'pancakes',cat:'desserts',price:420,weight:'240 г / g',image:'amber-pancakes.jpg',ru:['Воздушные панкейки','Пышная стопка с ягодами и сиропом.','Мягкие панкейки, приготовленные на заказ. Подаём с ягодами и сиропом — для неспешного завтрака или сладкого завершения обеда.','Мука, молоко, яйца, сахар, масло, ягоды, сироп. Аллергены: пшеница, молоко, яйца.'],en:['Fluffy pancakes','A soft stack with berries and syrup.','Fluffy pancakes made to order and topped with berries and syrup. Perfect for a leisurely breakfast or a sweet finish to lunch.','Flour, milk, eggs, sugar, butter, berries, syrup. Allergens: wheat, milk, eggs.']},
    {id:'coffee',cat:'drinks',price:250,weight:'250 мл / ml',image:'amber-coffee.jpg',ru:['Капучино','Эспрессо под шапкой молочной пены.','Двойной эспрессо из свежеобжаренных зёрен и молоко, взбитое до бархатной текстуры. Сбалансированный вкус с мягкими шоколадными нотами.','Кофе, молоко. Аллерген: молоко.'],en:['Cappuccino','Espresso topped with velvety milk foam.','A double espresso made with freshly roasted beans and silky steamed milk. A balanced cup with gentle chocolate notes.','Coffee, milk. Allergen: milk.']}
  ];
  const categories={all:['Всё меню','All dishes'],starters:['Салаты и боулы','Salads & bowls'],hot:['Горячее','Mains'],desserts:['Десерты','Desserts'],drinks:['Напитки','Drinks']};
  let lang='ru',category='all',cart={},detailId=null,toastTimer;
  try{lang=localStorage.getItem('boblirest.language')==='en'?'en':'ru';const saved=JSON.parse(localStorage.getItem('boblirest.cart')||'{}');for(const d of dishes){const n=saved?.[d.id];if(Number.isInteger(n)&&n>0)cart[d.id]=Math.min(n,99);}}catch{}
  const $=s=>document.querySelector(s), t=(ru,en)=>lang==='ru'?ru:en;
  const money=n=>new Intl.NumberFormat(lang==='ru'?'ru-RU':'en-US',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(n);
  const selected=()=>dishes.filter(d=>cart[d.id]);
  const total=()=>selected().reduce((n,d)=>n+d.price*cart[d.id],0);
  const store=()=>{try{localStorage.setItem('boblirest.cart',JSON.stringify(cart));}catch{}};
  function notify(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('visible');toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2200);}
  function renderGrid(){
    $('#filters').innerHTML=Object.entries(categories).map(([id,labels])=>`<button data-category="${id}" aria-pressed="${category===id}">${labels[lang==='ru'?0:1]}</button>`).join('');
    $('#dish-grid').innerHTML=dishes.filter(d=>category==='all'||d.cat===category).map(d=>`<article class="dish-card"><button class="dish-photo" data-detail="${d.id}" aria-label="${t('Подробнее: ','Details: ')+d[lang][0]}"><img src="photos/${d.image}" alt="${d[lang][0]}" loading="lazy" width="900" height="620"><span class="photo-hint">${t('Подробнее ↗','Discover ↗')}</span></button><div class="dish-body"><span class="dish-meta">${categories[d.cat][lang==='ru'?0:1]} · ${d.weight}</span><h2>${d[lang][0]}</h2><p>${d[lang][1]}</p><div class="dish-bottom"><span class="price">${money(d.price)}</span><button class="add" data-add="${d.id}" aria-label="${t('Добавить: ','Add: ')+d[lang][0]}">+</button></div></div></article>`).join('');
  }
  function renderDetail(){const d=dishes.find(d=>d.id===detailId);if(!d)return;$('#detail-content').innerHTML=`<img class="detail-image" src="photos/${d.image}" alt="${d[lang][0]}"><div class="dialog-body"><p class="eyebrow">${categories[d.cat][lang==='ru'?0:1]} · ${d.weight}</p><h2 id="detail-title">${d[lang][0]}</h2><p>${d[lang][2]}</p><p class="ingredients muted">${d[lang][3]}</p><button class="gold-button" data-add="${d.id}">${t('Добавить в корзину','Add to basket')} · ${money(d.price)}</button><p id="detail-count" class="muted" aria-live="polite"></p></div>`;updateDetailCount();}
  function updateDetailCount(){const el=$('#detail-count');if(el)el.textContent=cart[detailId]?t('В корзине: ','In basket: ')+cart[detailId]:'';}
  function renderCart(){
    $('#cart-count').textContent=Object.values(cart).reduce((a,b)=>a+b,0);
    $('#cart-items').innerHTML=selected().map(d=>`<div class="cart-row"><img src="photos/${d.image}" alt=""><div><h3>${d[lang][0]}</h3><p>${money(d.price)} × ${cart[d.id]} = ${money(d.price*cart[d.id])}</p></div><div class="quantity"><button data-change="${d.id}" data-step="-1" aria-label="${t('Уменьшить: ','Decrease: ')+d[lang][0]}">−</button><span>${cart[d.id]}</span><button data-change="${d.id}" data-step="1" aria-label="${t('Увеличить: ','Increase: ')+d[lang][0]}" ${cart[d.id]>=99?'disabled':''}>+</button></div></div>`).join('')||`<p class="empty">${t('Пока здесь пусто. Выберите что-нибудь вкусное в меню.','Your basket is empty. Discover something delicious on the menu.')}</p>`;
    $('#cart-summary').innerHTML=selected().length?`<div class="total"><span>${t('Итого','Total')}</span><span>${money(total())}</span></div><button id="show-waiter" class="gold-button">${t('Показать официанту','Show the waiter')} ↗</button><p class="muted">${t('Список не отправляется автоматически.','This list is not sent automatically.')}</p>`:'';
    $('#waiter-items').innerHTML=selected().map(d=>`<div class="waiter-row"><div>${d[lang][0]}<small>${money(d.price)} / ${t('порция','serving')}</small></div><div><strong>× ${cart[d.id]}</strong><small>${money(d.price*cart[d.id])}</small></div></div>`).join('')+`<div class="total"><span>${t('Итого','Total')}</span><span>${money(total())}</span></div>`;
    updateDetailCount();
  }
  function add(id){if((cart[id]||0)>=99){notify(t('Максимум 99 порций одного блюда','Maximum 99 servings per dish'));return;}cart[id]=(cart[id]||0)+1;store();renderCart();notify(t('Блюдо добавлено в корзину','Added to your basket'));}
  function applyLanguage(){document.documentElement.lang=lang;document.title=t('Меню — BobliRest','Menu — BobliRest');document.querySelectorAll('[data-ru]').forEach(e=>e.textContent=e.dataset[lang]);document.querySelectorAll('[data-language]').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.language===lang)));document.querySelectorAll('[data-close]').forEach(e=>e.setAttribute('aria-label',t('Закрыть','Close')));$('#filters').setAttribute('aria-label',t('Категории','Categories'));$('#dish-grid').setAttribute('aria-label',t('Блюда','Dishes'));renderGrid();renderCart();renderDetail();try{localStorage.setItem('boblirest.language',lang);}catch{}}
  document.addEventListener('click',e=>{
    const button=e.target.closest('button');if(!button)return;
    if(button.dataset.language){lang=button.dataset.language;applyLanguage();}
    if(button.dataset.category){category=button.dataset.category;renderGrid();$('#filters').querySelector(`[data-category="${category}"]`).focus();}
    if(button.dataset.detail){detailId=button.dataset.detail;renderDetail();$('#detail-dialog').showModal();}
    if(button.dataset.add)add(button.dataset.add);
    if(button.dataset.change){const id=button.dataset.change,step=Number(button.dataset.step);cart[id]=Math.min(99,(cart[id]||0)+step);if(cart[id]<=0)delete cart[id];store();renderCart();const replacement=$('#cart-items').querySelector(`[data-change="${id}"][data-step="${step}"]`)||$('#cart-dialog [data-close]');replacement.focus();}
    if(button.id==='open-cart'){renderCart();$('#cart-dialog').showModal();}
    if(button.id==='show-waiter')$('#waiter-dialog').showModal();
    if(button.hasAttribute('data-close'))button.closest('dialog').close();
  });
  document.querySelectorAll('dialog').forEach(dialog=>{dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});});
  applyLanguage();
})();
